# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import verification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        ('accounts', '0004_auto_20160709_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=' ', help_text='간단한 설명', max_length=200, null=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='시작일', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='종료일', null=True)),
                ('board', models.ForeignKey(blank=True, help_text='게시판 정보', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Board')),
                ('user', models.ForeignKey(blank=True, help_text='인증 토픽을 생성한 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser')),
            ],
            options={
                'ordering': ('-pk', 'start_date'),
            },
        ),
        migrations.CreateModel(
            name='VerificationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_image', models.ImageField(blank=True, help_text='인증 첨부파일', null=True, upload_to=verification.models.get_verification_file_path)),
                ('is_checked', models.BooleanField(default='False', help_text='인증여부')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='인증 업로드 날짜')),
                ('checked_date', models.DateTimeField(auto_now=True, help_text='인증 확인 날짜')),
                ('rank', models.IntegerField(default='0', help_text='인증 순위(스터디장이 결정)')),
                ('user', models.ForeignKey(blank=True, help_text='인증 완료한 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser')),
                ('verification', models.ForeignKey(blank=True, help_text='인증 정보', null=True, on_delete=django.db.models.deletion.CASCADE, to='verification.Verification')),
            ],
            options={
                'ordering': ('-pk', 'upload_date'),
            },
        ),
    ]
