# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(to='issue.IssueTag'),
        ),
    ]
