# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20160617_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='issuecomment',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='issuefile',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='issuelike',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='issuetag',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
