# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_auto_20160709_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='contents',
            field=models.TextField(blank=True, help_text='내용', null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(help_text='제목', max_length=200),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='contents',
            field=models.TextField(help_text='내용'),
        ),
    ]
