# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_auto_20160709_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_users', to='accounts.NanumUser'),
        ),
    ]
