# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_auto_20160709_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecomment',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issue.Issue'),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='user',
            field=models.ForeignKey(help_text='작성자', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_comment_users', to='accounts.NanumUser'),
        ),
        migrations.AlterField(
            model_name='issuefile',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issue.Issue'),
        ),
    ]
