# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import study.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20160709_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0, help_text='게시판의 종류 값')),
                ('title', models.CharField(default='이름 없음', help_text='게시판 이름', max_length=200)),
                ('nickname', models.CharField(blank=True, default='닉네임', help_text='게시판 별명', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=' ', help_text='간단한 설명', max_length=200, null=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='이름', max_length=200)),
                ('topic', models.CharField(help_text='주제', max_length=200)),
                ('thumbnail', models.ImageField(blank=True, help_text='썸네일 이미지', null=True, upload_to=study.models.get_study_thumbnail_path)),
                ('start_date', models.DateTimeField(blank=True, help_text='시작일', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='종료일', null=True)),
                ('joined_user_count', models.IntegerField(default=0, help_text='스터디 인원')),
                ('max_user_count', models.IntegerField(default=10, help_text='최대 스터디 인원')),
                ('like_count', models.IntegerField(default=0, help_text='좋아요 수')),
                ('is_active', models.BooleanField(default=True, help_text='스터디 진행여부(진행중/끝)')),
                ('is_enrolling', models.BooleanField(default=True, help_text='스터디 모집중(참여가능/불가)')),
            ],
            options={
                'ordering': ('-pk', '-start_date'),
            },
        ),
        migrations.CreateModel(
            name='StudyLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='좋아요 누른 날짜')),
                ('study', models.ForeignKey(blank=True, help_text='스터디 정보', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Study')),
                ('user', models.ForeignKey(blank=True, help_text='좋아요를 생성한 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser')),
            ],
            options={
                'ordering': ('-pk', '-create_date'),
            },
        ),
        migrations.CreateModel(
            name='StudyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True, help_text='스터디 참가일')),
                ('study', models.ForeignKey(blank=True, help_text='스터디 정보', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Study')),
                ('user', models.ForeignKey(blank=True, help_text='스터디에 참가한 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser')),
            ],
            options={
                'ordering': ('-pk', '-joined_date'),
            },
        ),
        migrations.AddField(
            model_name='study',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', through='study.StudyLike', to='accounts.NanumUser'),
        ),
        migrations.AddField(
            model_name='study',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', through='study.StudyMember', to='accounts.NanumUser'),
        ),
        migrations.AddField(
            model_name='board',
            name='study',
            field=models.ForeignKey(blank=True, help_text='스터디 정보', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Study'),
        ),
    ]
