# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import study.models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calender',
            options={'ordering': ('-pk', '-start_date')},
        ),
        migrations.AlterModelOptions(
            name='calendercategory',
            options={'ordering': ('-pk', 'name')},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-pk', '-create_date')},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('-pk', '-joined_date')},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ('-pk', '-create_date')},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-pk', '-create_date')},
        ),
        migrations.AlterModelOptions(
            name='questioncomment',
            options={'ordering': ('-pk', 'create_date')},
        ),
        migrations.AlterModelOptions(
            name='questionfile',
            options={'ordering': ('-pk', 'create_date')},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ('-pk', '-create_date')},
        ),
        migrations.AlterModelOptions(
            name='referencecomment',
            options={'ordering': ('-pk', 'create_date')},
        ),
        migrations.AlterModelOptions(
            name='referencefile',
            options={'ordering': ('-pk', 'create_date')},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ('-pk', '-start_date')},
        ),
        migrations.RenameField(
            model_name='like',
            old_name='create_data',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='joined_data',
            new_name='joined_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='position',
        ),
        migrations.AlterField(
            model_name='calender',
            name='description',
            field=models.TextField(blank=True, help_text='일정 설명', null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='is_part_time',
            field=models.BooleanField(help_text='시간 일정 여부'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='study',
            field=models.ForeignKey(blank=True, help_text='스터디', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Study'),
        ),
        migrations.AlterField(
            model_name='calendercategory',
            name='calender',
            field=models.ForeignKey(blank=True, help_text='일정 정보', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Calender'),
        ),
        migrations.AlterField(
            model_name='calendercategory',
            name='name',
            field=models.CharField(help_text='일정 분류', max_length=50),
        ),
        migrations.AlterField(
            model_name='like',
            name='study',
            field=models.ForeignKey(blank=True, help_text='스터디 정보', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Study'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, help_text='좋아요를 생성한 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AlterField(
            model_name='member',
            name='study',
            field=models.ForeignKey(blank=True, help_text='스터디 정보', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Study'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(blank=True, help_text='스터디에 참가한 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='study',
            field=models.ForeignKey(blank=True, help_text='스터디', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Study'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(blank=True, help_text='작성자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AlterField(
            model_name='question',
            name='study',
            field=models.ForeignKey(blank=True, help_text='질문글이 포함된 스터디', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Study'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, help_text='질문글을 생성한 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='question',
            field=models.ForeignKey(blank=True, help_text='댓글에 대한 상위 질문', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Question'),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='질문글에 대한 댓글을 생성한 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AlterField(
            model_name='questionfile',
            name='attached_file',
            field=models.FileField(blank=True, help_text='질문글에 대한 첨부파일', null=True, upload_to=study.models.get_question_file_path),
        ),
        migrations.AlterField(
            model_name='questionfile',
            name='question',
            field=models.ForeignKey(blank=True, help_text='첨부파일이 포함된 질문글', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Question'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='calender',
            field=models.ForeignKey(blank=True, help_text='참고자료와 관련된 일정', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Calender'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='study',
            field=models.ForeignKey(blank=True, help_text='참고자료와 관련된 스터디', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Study'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='user',
            field=models.ForeignKey(blank=True, help_text='참고자료를 업로드한 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AlterField(
            model_name='referencecomment',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='참고자료', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Reference'),
        ),
        migrations.AlterField(
            model_name='referencecomment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='참고자료에 대한 댓글', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AlterField(
            model_name='referencefile',
            name='attached_file',
            field=models.FileField(blank=True, help_text='첨부한 참고자료', null=True, upload_to=study.models.get_reference_file_path),
        ),
        migrations.AlterField(
            model_name='referencefile',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='참고자료에 대한 정보', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Reference'),
        ),
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='종료일', null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='is_active',
            field=models.BooleanField(default=True, help_text='스터디 진행여부(진행중/끝)'),
        ),
        migrations.AlterField(
            model_name='study',
            name='is_enrolling',
            field=models.BooleanField(default=True, help_text='스터디 모집중(참여가능/불가)'),
        ),
        migrations.AlterField(
            model_name='study',
            name='max_user_count',
            field=models.IntegerField(default=10, help_text='최대 스터디 인원'),
        ),
        migrations.AlterField(
            model_name='study',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='시작일', null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='썸네일 이미지', null=True, upload_to=study.models.get_study_thumbnail_path),
        ),
    ]
