# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='study_likes', through='study.StudyLike', to='accounts.NanumUser'),
        ),
    ]
