# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20160829_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='typename',
            field=models.CharField(default=' ', help_text='게시판 종류 이름', max_length=200),
        ),
    ]
