# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20160812_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='일정 분류', max_length=50)),
                ('calender', models.ManyToManyField(blank=True, help_text='일정 정보', related_name='calendertag_set', to='study.Calender')),
            ],
            options={
                'ordering': ('-pk', 'name'),
            },
        ),
        migrations.RemoveField(
            model_name='calendercategory',
            name='calender',
        ),
        migrations.DeleteModel(
            name='CalenderCategory',
        ),
    ]
