# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_board_typename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='typename',
        ),
    ]
