# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20160813_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='title',
            field=models.CharField(default='제목없음', help_text='일정 제목', max_length=200),
            preserve_default=False,
        ),
    ]
