# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_calender_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='is_oneday',
            field=models.BooleanField(default=False, help_text='종일 일정 여부'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='is_part_time',
            field=models.BooleanField(default=False, help_text='시간 일정 여부'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='title',
            field=models.CharField(default='제목없는 일정', help_text='일정 제목', max_length=200),
        ),
    ]
