# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import reference.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=200)),
                ('contents', models.TextField(blank=True, help_text='내용', null=True)),
                ('count', models.IntegerField(default=0, help_text='조회수')),
                ('comment_count', models.IntegerField(default=0, help_text='댓글 수')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='작성일')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정일')),
            ],
            options={
                'ordering': ('-pk', '-create_date'),
            },
        ),
        migrations.CreateModel(
            name='ReferenceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='파일 이름', max_length=200)),
                ('size', models.CharField(help_text='파일 크기(kb) in char type', max_length=200)),
                ('download_count', models.IntegerField(default=0, help_text='다운로드 횟수')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('attached_file', models.FileField(blank=True, help_text='첨부한 참고자료', null=True, upload_to=reference.models.get_reference_file_path)),
                ('reference', models.ForeignKey(blank=True, help_text='참고자료에 대한 정보', null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Reference')),
            ],
            options={
                'ordering': ('-pk', 'create_date'),
            },
        ),
    ]
