# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 11:30
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='NanumUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthday', models.DateField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.get_file_path)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
