# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160617_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanumuser',
            name='test_field',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='nanumuser',
            name='birthday',
            field=models.DateField(blank=True, help_text='생일', null=True),
        ),
    ]
