# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160709_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nanumuser',
            name='test_field',
        ),
        migrations.AlterModelTable(
            name='nanumuser',
            table='nanum_user',
        ),
    ]
