# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='제목없는 일정', help_text='일정 제목', max_length=200)),
                ('start_date', models.DateTimeField(help_text='일정 시작일')),
                ('end_date', models.DateTimeField(help_text='일정 종료일')),
                ('description', models.TextField(blank=True, help_text='일정 설명', null=True)),
                ('is_oneday', models.BooleanField(default=False, help_text='종일 일정 여부')),
                ('color', models.CharField(blank=True, default='#FFFFFF', help_text='일정 색상', max_length=200, null=True)),
                ('linked_type', models.IntegerField(default=-1, help_text='일정과 관련된 글의 종류(과제, 자료 등)')),
            ],
            options={
                'ordering': ('-pk', '-start_date'),
            },
        ),
        migrations.CreateModel(
            name='ScheduleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='일정 분류', max_length=50)),
                ('schedule', models.ManyToManyField(blank=True, help_text='일정 정보', related_name='schedule_tag_set', to='schedule.Schedule')),
            ],
            options={
                'ordering': ('-pk', 'name'),
            },
        ),
    ]
