# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20160829_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, help_text='일정 종료일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, help_text='일정 시작일'),
        ),
    ]
