# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160709_0430'),
        ('basic_board', '0002_auto_20160829_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicBoardLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='좋아요 누른 날짜')),
                ('basic_board', models.ForeignKey(blank=True, help_text='게시글 정보', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_board.BasicBoard')),
                ('user', models.ForeignKey(blank=True, help_text='좋아요 생성 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser')),
            ],
            options={
                'ordering': ('-pk', '-create_date'),
            },
        ),
        migrations.AddField(
            model_name='basicboard',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='basic_board_likes', through='basic_board.BasicBoardLike', to='accounts.NanumUser'),
        ),
    ]
