# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import homework.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20160709_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=200)),
                ('contents', models.TextField(blank=True, help_text='내용', null=True)),
                ('count', models.IntegerField(default=0, help_text='조회수')),
                ('comment_count', models.IntegerField(default=0, help_text='댓글 수')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='작성일')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('end_date', models.DateTimeField(help_text='과제 마감일')),
                ('finished_count', models.DateTimeField(default=0, help_text='과제 제출한 스터디원 수')),
            ],
            options={
                'ordering': ('-pk', '-create_date'),
            },
        ),
        migrations.CreateModel(
            name='HomeWorkFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='파일 이름', max_length=200)),
                ('size', models.CharField(help_text='파일 크기(kb) in char type', max_length=200)),
                ('download_count', models.IntegerField(default=0, help_text='다운로드 횟수')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('attached_file', models.FileField(blank=True, help_text='과제 첨부 파일', null=True, upload_to=homework.models.get_homework_file_path)),
                ('homework', models.ForeignKey(blank=True, help_text='첨부파일이 속한 과제', null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.HomeWork')),
                ('user', models.ForeignKey(blank=True, help_text='과제를 제출한 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser')),
            ],
            options={
                'ordering': ('-pk', 'create_date'),
            },
        ),
    ]
