# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20160709_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedFIle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='파일 이름', max_length=200)),
                ('size', models.CharField(help_text='파일 크기(kb) in char type', max_length=200)),
                ('download_count', models.IntegerField(default=0, help_text='다운로드 횟수')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('attached_file', models.FileField(help_text='과제 첨부 파일', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(help_text='내용')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='작성일')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정일')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(help_text='내용')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='작성일')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정일')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=200)),
                ('contents', models.TextField(blank=True, help_text='내용', null=True)),
                ('count', models.IntegerField(default=0, help_text='조회수')),
                ('comment_count', models.IntegerField(default=0, help_text='댓글 수')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='작성일')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('end_date', models.DateTimeField(help_text='과제 마감일')),
                ('finished_count', models.DateTimeField(default=0, help_text='과제 제출한 스터디원 수')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(help_text='내용')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='작성일')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('feedback_count', models.IntegerField(default=0, help_text='피드백 수')),
                ('is_finished', models.BooleanField(help_text='제출 완료 여부')),
                ('homework', models.ForeignKey(help_text='과제', on_delete=django.db.models.deletion.CASCADE, to='homework.HomeWork')),
                ('user', models.ForeignKey(help_text='과제 제출자', on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmitFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='파일 이름', max_length=200)),
                ('size', models.CharField(help_text='파일 크기(kb) in char type', max_length=200)),
                ('download_count', models.IntegerField(default=0, help_text='다운로드 횟수')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('attached_file', models.FileField(help_text='첨부 파일', upload_to='')),
                ('submit', models.ForeignKey(help_text='과제 첨부 파일 댓글', on_delete=django.db.models.deletion.CASCADE, to='homework.Submit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
