# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        ('homework', '0001_initial'),
        ('accounts', '0004_auto_20160709_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='study',
            field=models.ForeignKey(help_text='과제가 속한 스터디', on_delete=django.db.models.deletion.CASCADE, to='study.Study'),
        ),
        migrations.AddField(
            model_name='homework',
            name='user',
            field=models.ForeignKey(help_text='과제 출제자', on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submit',
            field=models.ForeignKey(help_text='과제 제출 글', on_delete=django.db.models.deletion.CASCADE, to='homework.Submit'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(help_text='피드백 작성자', on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='homework',
            field=models.ForeignKey(help_text='과제', on_delete=django.db.models.deletion.CASCADE, to='homework.HomeWork'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='댓글 작성자', on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='homework',
            field=models.ForeignKey(help_text='첨부파일이 속한 과제', on_delete=django.db.models.deletion.CASCADE, to='homework.HomeWork'),
        ),
    ]
