# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homework', '0001_initial'),
        ('study', '0001_initial'),
        ('accounts', '0004_auto_20160709_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='study',
            field=models.ForeignKey(blank=True, help_text='과제가 속한 스터디', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Study'),
        ),
        migrations.AddField(
            model_name='homework',
            name='user',
            field=models.ForeignKey(blank=True, help_text='과제 출제자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
    ]
