# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import homework.models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        ('accounts', '0004_auto_20160709_0430'),
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWorkFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='파일 이름', max_length=200)),
                ('size', models.CharField(help_text='파일 크기(kb) in char type', max_length=200)),
                ('download_count', models.IntegerField(default=0, help_text='다운로드 횟수')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('attached_file', models.FileField(blank=True, help_text='과제 첨부 파일', null=True, upload_to=homework.models.get_homework_file_path)),
            ],
            options={
                'ordering': ('-pk', 'create_date'),
            },
        ),
        migrations.DeleteModel(
            name='AttachedFIle',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='submitfile',
            name='submit',
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('-pk', '-create_date')},
        ),
        migrations.AddField(
            model_name='homework',
            name='study',
            field=models.ForeignKey(blank=True, help_text='과제가 속한 스터디', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Study'),
        ),
        migrations.AddField(
            model_name='homework',
            name='user',
            field=models.ForeignKey(blank=True, help_text='과제 출제자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.DeleteModel(
            name='Submit',
        ),
        migrations.DeleteModel(
            name='SubmitFile',
        ),
        migrations.AddField(
            model_name='homeworkfile',
            name='homework',
            field=models.ForeignKey(blank=True, help_text='첨부파일이 속한 과제', null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.HomeWork'),
        ),
        migrations.AddField(
            model_name='homeworkfile',
            name='user',
            field=models.ForeignKey(blank=True, help_text='과제를 제출한 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
    ]
