# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import homework.models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20160727_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachedfile',
            options={'ordering': ('-pk', 'create_date')},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pk', 'create_date')},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-pk', 'create_date')},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('-pk', '-create_date')},
        ),
        migrations.AlterModelOptions(
            name='submit',
            options={'ordering': ('-pk', 'create_date')},
        ),
        migrations.AlterModelOptions(
            name='submitfile',
            options={'ordering': ('-pk', 'create_date')},
        ),
        migrations.AlterField(
            model_name='attachedfile',
            name='attached_file',
            field=models.FileField(blank=True, help_text='과제 첨부 파일', null=True, upload_to=homework.models.get_attached_file_path),
        ),
        migrations.AlterField(
            model_name='attachedfile',
            name='homework',
            field=models.ForeignKey(blank=True, help_text='첨부파일이 속한 과제', null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.HomeWork'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='homework',
            field=models.ForeignKey(blank=True, help_text='과제', null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.HomeWork'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='댓글 작성자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='submit',
            field=models.ForeignKey(blank=True, help_text='과제 제출 글', null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.Submit'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, help_text='피드백 작성자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='study',
            field=models.ForeignKey(blank=True, help_text='과제가 속한 스터디', null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Study'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='user',
            field=models.ForeignKey(blank=True, help_text='과제 출제자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='homework',
            field=models.ForeignKey(blank=True, help_text='과제', null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.HomeWork'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='제출 완료 여부'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='user',
            field=models.ForeignKey(blank=True, help_text='과제 제출자', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.NanumUser'),
        ),
        migrations.AlterField(
            model_name='submitfile',
            name='attached_file',
            field=models.FileField(blank=True, help_text='첨부 파일', null=True, upload_to=homework.models.get_submit_file_path),
        ),
        migrations.AlterField(
            model_name='submitfile',
            name='submit',
            field=models.ForeignKey(blank=True, help_text='과제 첨부 파일 댓글', null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.Submit'),
        ),
    ]
