# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20160829_1133'),
        ('homework', '0002_auto_20160829_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='과제 일정', null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule'),
        ),
    ]
